version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        command: ./start.sh
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: innyx_db
            MYSQL_USER: default
            MYSQL_PASSWORD: 12345678
            MYSQL_ROOT_PASSWORD: 12345678
        ports:
            - "3306:3306"
